### ISSUE TITLE
Derak Cdn

### ISSUE THREAD

**Issue by amiranbari** [miladrahimi/v2ray-docker-compose#103]
Hi , I tried to connect with derak cdn.
but it does not work with the proxy on.
Do you have better idea or any solution for this ?

**Comment by MJamshidnejad** [comment]
> Hi , I tried to connect with derak cdn. but it does not work with the proxy on. Do you have better idea or any solution for this ?

It's possible, but there are some hints, such as the fact only 80 and 433 ports are available. However, because of their instability and inconsistency in their service-providing method, I don't recommend you use it.

**Comment by amiranbari** [comment]
So what method would you suggest so that the server is not filtered and we can connect to it?

**Comment by MJamshidnejad** [comment]
> So what method would you suggest so that the server is not filtered and we can connect to it?

There's no guaranteed method to avoid a ban. The most important thing to remember is that your server must emulate a real HTTP server.

**Comment by amiranbari** [comment]
> > So what method would you suggest so that the server is not filtered and we can connect to it?
> 
> There's no guaranteed method to avoid a ban. The most important thing to remember is that your server must emulate a real HTTP server.

Thanks for you helping. Do you know how can i connect a domain to my server for showing a website and using the v2ray-nginx-cdn together ?

**Comment by Mchisd** [comment]
try Cloudflare Bro
