### ISSUE TITLE
V2ray-caddy-cdn only works on rightel

### ISSUE THREAD

**Issue by Mchisd** [miladrahimi/v2ray-docker-compose#104]
hi 
i run V2ray-caddy-cdn(cloudflare)
and it work verywell on rightel but i cant use video call on this
and 
it not work on any isp(adsl,mci,mtnir)

**Comment by miladrahimi** [comment]
Probably the IP that Cloudflare has assigned to your domain is blocked by that operator.
You can replace your domain with non-blocked Cloudflare IP or you should try Arvan or other CDNs.
