### ISSUE TITLE
Feature Request: Xray-core v1.8.0

### ISSUE THREAD

**Issue by mostafasoufi** [miladrahimi/v2ray-docker-compose#108]
Hey,

I see that [Xray-core v1.8.0](https://github.com/XTLS/Xray-core/releases), which supports the reality protocol, has been released. Is there any intention to update the core?

@miladrahimi

**Comment by miladrahimi** [comment]
Dear @mostafasoufi we use v2ray (by v2fly) in this repository and it won't be replaced with xray.
