### ISSUE TITLE
V2Ray Upsream and Bridge Servers does not work with Irancell/RighTel for some bridge servers

### ISSUE THREAD

**Issue by asajadian** [miladrahimi/v2ray-docker-compose#112]
Hi. First thanks for the awesome repo, have helped keep a dozens of people connected!

I'm using `V2Ray Upsream and Bridge Servers` method. It's worked fine for the past ~9 months with all operators and ISPs. Recently I bought a new vps from a provider in a new datacenter (in Iran to use as bridge).
But it does not work with Irancell/RighTel. HarahAval is OK. I have no idea what the issue is.
Any help would be appreciated.

**Comment by miladrahimi** [comment]
Hi, I've also seen this issue but I couldn't find any solution for it. I just changed the Iran server and eventually find one that works with those providers (try ArvanCloud). There is nothing wrong with your configurations.
