### ISSUE TITLE
Docker image repo in github not support same of os

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/v2ray-docker-compose#114]
Please change github package v2fly-core

Form `ghcr.io/getimages/v2fly-core:v4.45.2` to main docker repo 
`v2fly/v2fly-core:v4.45.2`

**Comment by miladrahimi** [comment]
I've mentioned here that you can change it yourself:
https://github.com/miladrahimi/v2ray-docker-compose?tab=readme-ov-file#docker-images
I've used the GitHub registry since it hasn't banned Iranian users.
