### ISSUE TITLE
change ports

### ISSUE THREAD

**Issue by Mr3rf1** [miladrahimi/v2ray-docker-compose#116]
how can i use 8443 instead of 443 and 8080 instead of 80 for nginx?
80 port of my server is busy.

**Comment by miladrahimi** [comment]
For now you can only do it manually by editing the docker-compose.yml files. It'd a good enhancement, You can fork this repository and and create a PR to fix this issue.

**Comment by miladrahimi** [comment]
You can read this: https://stackoverflow.com/questions/51209710/specify-caddy-listening-port
