### ISSUE TITLE
please add allow firewall

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/v2ray-docker-compose#118]
add new help command in relay server
` sudo ufw allow 8000`

**Comment by miladrahimi** [comment]
Thanks for your suggestion, added.

**Comment by vahidalvandi** [comment]
also add `sudo ufw allow OpenSSH` and `sudo ufw enabel`

**Comment by miladrahimi** [comment]
Allowing the OpenSSH port or forcing users to enable UFW is not relevant in our context.
