### ISSUE TITLE
Proxy DNS  requests to the upstream server

### ISSUE THREAD

**Issue by mohsenk** [miladrahimi/v2ray-docker-compose#19]
Hi
In last 3 days, I believe they are doing some actions on the DNS packets. and you can not browse internet with v2ray.  I just works for Telegram and some other applications.
As I saw in this config we are solving the DNS in the bridge server. 
How we can proxy the DNS requests to the upstream servers too ?

Thank you.

**Comment by itsamirhn** [comment]
I have the same issue with mobile clients.

**Comment by ohmydevops** [comment]
Can you delete DNS object from bridge and test again?
