### ISSUE TITLE
Is it possible to use the new `quic` transport?

### ISSUE THREAD

**Issue by ATheCoder** [miladrahimi/v2ray-docker-compose#22]
As you know, the websocket transport is much more slower than **TCP**. The `quic` protocol was introduced in **V2ray-4.7** and it promises a faster and more stealthy transport. Has anybody tried using it?

I searched around and found some sample configurations however I couldn't manage to make it work.

**Comment by miladrahimi** [comment]
Dear @ATheCoder, the docker image contains V2Ray version 4.22.1 which doesn't support QUIC.

**Comment by ATheCoder** [comment]
Correct me If I'm wrong but isn't **22 > 7**?

You can visit the [release page for v2fly](https://github.com/v2fly/v2ray-core/tags) to make sure.

As you can see [4.7.3](https://github.com/v2fly/v2ray-core/tags?after=v4.14.1) was release on **04/Dec/2018** and [4.22.0](https://github.com/v2fly/v2ray-core/tags?after=v4.23.4) was released on **22/Dec/2019**.
