### ISSUE TITLE
Feature branch for test new ideas

### ISSUE THREAD

**Issue by ohmydevops** [miladrahimi/v2ray-docker-compose#28]
For example, to using [v5.1.0](https://github.com/v2fly/v2ray-core/releases/tag/v5.1.0), we need to test and ensure everything is working properly; because it is a user preview version.
I can test and report results for new features.

**Comment by ohmydevops** [comment]
We must have feature branches for this type of changes.

**Comment by miladrahimi** [comment]
I've just tested and then updated. I think if there is no problem with new versions we can update. Since it's not a app, versioning might be useless.
It you found any issue please let me know to revert to the previos version.

**Comment by miladrahimi** [comment]
You were right, I changed it to v2fly-core:v4.45.2
