### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by amirrezaask** [miladrahimi/v2ray-docker-compose#32]
It would be nice if we include a setup script for easy setup so for new users we do something like
```bash
curl github.com/miladrahimi/v2ray-docker-compose/tree/master/setup.sh | bash
```
script should:
- check if docker and docker-compose are installed, if not abort.
- ask for bridge mode or upstream mode.
- asks users for UUID and provides default behavior for generating one.
- format config file with appropriate values
- ask the user whether to start serving or not 

Or
we can do a different approach and do a client side script that will take two ips as bridge and upstream and setup servers using ssh itself, it's the most user friendly and easy way

**Comment by ohmydevops** [comment]
I'm working on this: https://github.com/ohmydevops/v2ray-ansible, but I think Ansible is not suitable for this work. (It is against simplicity).

I can work on scripts for debian-based servers.

**Comment by ohmydevops** [comment]
But we want a cross-os solution, as simple as running `curl .....`

**Comment by ohmydevops** [comment]
> It would be nice if we include a setup script for easy setup so for new users we do something like
> 
> ```shell
> curl github.com/miladrahimi/v2ray-docker-compose/tree/master/setup.sh | bash
> ```
> 
> script should:
> 
> * check if docker and docker-compose are installed, if not abort.
> * ask for bridge mode or upstream mode.
> * asks users for UUID and provides default behavior for generating one.
> * format config file with appropriate values
> * ask the user whether to start serving or not
> 
> Or we can do a different approach and do a client side script that will take two ips as bridge and upstream and setup servers using ssh itself, it's the most user friendly and easy way

- add new Vmess client (interactive)
