### ISSUE TITLE
Create vmess base64 strings from config.json

### ISSUE THREAD

**Issue by ohmydevops** [miladrahimi/v2ray-docker-compose#34]
Users can use [this scripts ](https://github.com/boypt/vmess2json/wiki/json2vmess) to generate all vmess clients base64 strings from `config.json`.

For example:
```shell
./json2vmess.py /to/path/config/config.json
```

**Comment by miladrahimi** [comment]
Thanks for your idea. I've created this file myself.
https://github.com/miladrahimi/v2ray-docker-compose/blob/master/v2ray-bridge-server/vmess.sh
