### ISSUE TITLE
some questions about updates

### ISSUE THREAD

**Issue by MJamshidnejad** [miladrahimi/v2ray-docker-compose#35]
I have read new version of the configuration files. I want to ask the reason of following changes:
- "alter id" changed to 0 (the document recommends 4).
- delete Iranian internal IPs that you had added to bridge config file (that was a nice idea. It avoids users to on and off VPN for internal usage)
- you changed streaming mode from tcp to ws in outbound bridge but you leaved inbound with tcp.
- the reason you did not use v2fly v5.1.0 .

thanks.

**Comment by miladrahimi** [comment]
Hello dear @MJamshidnejad 
* Alter ID is deprecated and you cannot use it in new versions of clients. It must be zero.
* They were only a very small number of Iranian IP ranges. They were not that much useful. IR domain rule still exists.
* The stream modes are:
    * It's "WS" between the bridge and upstream servers because TCP didn't work without obfuscation, and it might be slower. The "WS" doesn't need more configurations, and it's cleaner!
    * It's "TCP" between client and bridge server because some clients don't support WS.
* v5.1.0 is a user preview version and not stable.

**Comment by MJamshidnejad** [comment]
Thanks for your prompt reply! :) 
As you should know, v2ray protocols are being blocked here. I'm confused by their method. sometimes, inbound blocked but outbound works in the bridge server while they are working on the same port. So it doesn't seem the method is port blocking. or sometimes a server works with a mobile service provider but not the other one! I experienced blocking by a CDN too! I would like to know do you have any idea about the parameters that are important in blocking like this or how they block the connections? using ws or tcp or other transport methods could be effective? I thought maybe the tcp headers that you have used could be effective!

**Comment by miladrahimi** [comment]
I use Outline/Shadowsocks personally and it works fine. But I check VMESS. Thanks for your report.

**Comment by MJamshidnejad** [comment]
Your welcome. If you want more information please let me know.

**Comment by miladrahimi** [comment]
Please use shadowsock to check if bridge-upstream connection is ok.
If it's ok, switch stream modes to check is there any chance one of them work.

**Comment by miladrahimi** [comment]
It seems there was a bug in VMESS, please update your docker-compose files and check it.

**Comment by MJamshidnejad** [comment]
> Please use shadowsock to check if bridge-upstream connection is ok. If it's ok, switch stream modes to check is there any chance one of them work.

bridge-upstream connection always is ok. I have to mention I use that tcp config. The problem is user-bridge connection. for the user I changed tcp to ws but it didn't change anything. I still have the blocked server. It's ok. it works fine. I can ping to that. but protocols (ss and vmess) don't work. If you have any idea I can do on the block server to test.

**Comment by MJamshidnejad** [comment]
> It seems there was a bug in VMESS, please update your docker-compose files and check it.

What bug? Is it about losing connection? I'll update asap and report the result.

**Comment by miladrahimi** [comment]
https://github.com/miladrahimi/v2ray-docker-compose/blob/master/v2ray-bridge-server/docker-compose.yml#L8

**Comment by MJamshidnejad** [comment]
> https://github.com/miladrahimi/v2ray-docker-compose/blob/master/v2ray-bridge-server/docker-compose.yml#L8

Sorry but why is it important? It didn't change anything in my setup.

**Comment by miladrahimi** [comment]
It caused some clients not to work. If nothing changes for you. ignore it.
I think you have to change your servers.

**Comment by MJamshidnejad** [comment]
> It caused some clients not to work. If nothing changes for you. ignore it. I think you have to change your servers.

Let me investigate it more. Sorry I took all of your day :) Thanks for your support pal ;)
