### ISSUE TITLE
New update does not work

### ISSUE THREAD

**Issue by h4med** [miladrahimi/v2ray-docker-compose#38]
Hi, 
Thanks for this useful repo. 
Almost a week ago I used this repo with two servers and every thing works just fine. 
Today I sat up two new servers from same companies as before with updated scripts but it does not work.
The test with V2RayNG is OK but internet is not available on the client.
I tried to use the old script from old servers but it seems that docker images are not available:

> 
> Pulling v2ray ([ghcr.io/miladrahimi/v2ray:latest](http://ghcr.io/miladrahimi/v2ray:latest))...
> ERROR: Head "https://ghcr.io/v2/miladrahimi/v2ray/manifests/latest": denied

Can you bring back the old images?

**Comment by h4med** [comment]
After further debugging I found out that in logs/access.log instead of directing the requests to Upstream IP, they are directed to some other IP which I guess is my Dynamic IP:
```
 tail -f logs/access.log
2022/10/24 19:29:34 <NOT-UPSTREAM-IP>:19666 accepted udp:1.1.1.1:53 [proxy]
2022/10/24 19:29:35 <NOT-UPSTREAM-IP>:58267 accepted tcp:www.google.com:80 [proxy]
2022/10/24 19:29:38 <NOT-UPSTREAM-IP>:25513 accepted udp:1.1.1.1:53 [proxy]
2022/10/24 19:29:38 tcp:<NOT-UPSTREAM-IP>:62457 accepted udp:216.239.35.8:123 [proxy]
.
.
```
Why? I set the Up-Stream IP address in config.json

**Comment by miladrahimi** [comment]
Please update docker-compose and config files and use the new image.

**Comment by h4med** [comment]
With the latest version I have the same problem. All traffic is routed to a strange IP instead of Upstream server (in access log)
Should I change any settings of VPS? or change my VPS provider?
