### ISSUE TITLE
Fallback Upstream Server(s)

### ISSUE THREAD

**Issue by iMasoud** [miladrahimi/v2ray-docker-compose#39]
Thanks for your fantastic solution. However, as you know, there is a good chance that upstream servers will become unreachable due to blind foreign IP range blockings by the Iranian government.

It would be great if we can configure two (or more) upstream servers for our bridge so it would fall back to the second one in case the first one is unreachable. It would improve this tool's reliability very much.

**Comment by miladrahimi** [comment]
Does v2ray support this feature?

**Comment by MJamshidnejad** [comment]
> Does v2ray support this feature?
I have no idea about the first!
about the second one, yes. you can set some servers in outbound and balance the load between them. but, it may not be a good solution for sites which block users that change their IP while using their services.

**Comment by iMasoud** [comment]
> Does v2ray support this feature?

Not sure. Didn't find anything like that in their docs. I've opened an issue but haven't received a response yet.

**Comment by iMasoud** [comment]
> > Does v2ray support this feature?
> 
> I have no idea about the first! about the second one, yes. you can set some servers in outbound and balance the load between them. but, it may not be a good solution for sites which block users that change their IP while using their services.

You're right. That's why I look for something other than load balancing. I described that the second outbound gets used only when the first one is unreachable.

**Comment by MJamshidnejad** [comment]
> > > Does v2ray support this feature?
> > 
> > 
> > I have no idea about the first! about the second one, yes. you can set some servers in outbound and balance the load between them. but, it may not be a good solution for sites which block users that change their IP while using their services.
> 
> You're right. That's why I look for something other than load balancing. I described that the second outbound gets used only when the first one is unreachable.

you know, to be honest, that's not a problem. you can change your upstream setting in a blink! you should just set an IP, id and port. There are really worse problems right now!

**Comment by MJamshidnejad** [comment]
> > > > Does v2ray support this feature?
> > > 
> > > 
> > > I have no idea about the first! about the second one, yes. you can set some servers in outbound and balance the load between them. but, it may not be a good solution for sites which block users that change their IP while using their services.
> > 
> > 
> > You're right. That's why I look for something other than load balancing. I described that the second outbound gets used only when the first one is unreachable.
> 
> you know, to be honest, that's not a big problem. you can change your upstream setting in a blink! you should just set an IP, id and port. you can even set a server and hold it up for an emergency. There are really worse problems right now!
