### ISSUE TITLE
Passing Iran's geo-ip traffic from upstream server

### ISSUE THREAD

**Issue by keikhosrow** [miladrahimi/v2ray-docker-compose#4]
Hi,
after the implementation, I noticed that Iran's geo-IP sites are trying to pass from upstream server traffic regardless of the routing configuration of the bridge server, the config.json file of the bridge server is untouched.
Am I missing something?
Truly, peace be upon you for this life saver.

**Comment by miladrahimi** [comment]
Unfortunately, the `geoip:ir` doesn't work properly. You can add IP ranges instead.
Sample IP ranges:
```json
"ip": [
        "192.168.0.0/24",
]
```
Your welcome. I hope this tool be helpful in this dark time :)

**Comment by keikhosrow** [comment]
I think that considering the fact that most Iranian services (public and private) are hosted by Arvan Cloud, it will be useful to exclude its IP ranges, I have prepared Arvan Cloud IP ranges in Json format.
I'll apply a pull request.
freedom is never given, it is won.

**Comment by keikhosrow** [comment]
freedom is never given, it is won.
