### ISSUE TITLE
Xray core and more suggestions.

### ISSUE THREAD

**Issue by cursedwraith** [miladrahimi/v2ray-docker-compose#42]
Hi
This is awesome solution but it would be easier to detect ?

Why not use Xray core instead of old v2ray core ? it is stronger.
also can we use other protocols such as vless or trojan 

Update:  i decided to turn this issue into some suggestion for future.

- [ ] Use Xray core instead
- [ ] Use of XTLS.
- [ ] Using rust port of shadowsocks
- [ ] Use other ciphers such as "2022-blake3-chacha20-poly1305", "chacha20-ietf-poly1305" etc... for shadowsocks
- [ ] Other protocols such as Brook, Trojan, VLESS ....
- [ ] Avoid Iran server detection by adding randomized download and upload TO and FROM the bridge server. (possibly by going to 1:10 ration ? as i read somewhere : "for each 10GB upload, you should have a 1GB download" + using dd to randmize file generation)

**Comment by miladrahimi** [comment]
As you can see the repo name, it's docker-compose files for ""v2ray"". For xray we have to create another repo. Since v2ray has more documentation and user, I prefer to use v2ray for now.
