### ISSUE TITLE
VMess and SS are detected by MTN Irancell Co.

### ISSUE THREAD

**Issue by mjafari98** [miladrahimi/v2ray-docker-compose#46]
We can not connect to the proxy servers either with ShadowSocks or VMess protocols via MTN Irancell. Is there any way or procedure to compass this situation?

**Comment by cursedwraith** [comment]
> We can not connect to the proxy servers either with ShadowSocks or VMess protocols via MTN Irancell. Is there any way or procedure to compass this situation?
Your upstream server might be blocked ? where did you buy your bridge server

**Comment by mjafari98** [comment]
> > We can not connect to the proxy servers either with ShadowSocks or VMess protocols via MTN Irancell. Is there any way or procedure to compass this situation?
> 
> Your upstream server might be blocked ? where did you buy your bridge server

No I don't think so. 
I tried another (new) service.
