### ISSUE TITLE
Any ways to set multiple username and password for vmess and limit bandwidth?

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [miladrahimi/v2ray-docker-compose#49]
Hi,

I read docs of v2ray and saw all parts of config file but did not find anything to set multiple usernames and passwords (something like account-based service).
Is there any way to do this? I saw some videos which require hardware ID and things like this, which is not acceptable in my mind.

Also I didn't find a way to limit per-container bandwidth in docker. Do you have any solution? This is when the first question could not be implemented, and it would be an alternative.

**Comment by miladrahimi** [comment]
I've not tested it myself but there is a project named x-ui:
https://github.com/vaxilu/x-ui
https://seakfind.github.io/2021/10/10/X-UI/
