### ISSUE TITLE
Some sanctioned websites cannot be accessed.

### ISSUE THREAD

**Issue by omid96** [miladrahimi/v2ray-docker-compose#54]
I believe some sanctioned sites cannot be accessed with the current configuration.

Examples: 

- https://spotify.com/
- https://cloud.google.com/

**Comment by MJamshidnejad** [comment]
> I believe some sanctioned sites cannot be accessed with the current configuration.
> 
> Examples:
> 
> * https://spotify.com/
> * https://cloud.google.com/

Share more information... Your device, service provider, configs, ....

**Comment by omid96** [comment]
Thanks for your response, I have directly connected to my upstream server and I found out that the problem is from my upstream server and not the configs. I will close this issue.

**Comment by miladrahimi** [comment]
It's related to your upstream server and your browsing behaviors. Those services might have banned your upstream IP address. They might recognize your origin by your Cookies.

**Comment by omid96** [comment]
Thanks for your response dear @miladrahimi. You are right that's exactly what happened. I don't know how to solve it or prevent it yet.

**Comment by omid96** [comment]
> Thanks for your response dear @miladrahimi. You are right that's exactly what happened. I don't know how to solve it or prevent it in the future yet.



> It's related to your upstream server and your browsing behaviors. Those services might have banned your upstream IP address. They might recognize your origin by your Cookies.

Thanks for your response dear @miladrahimi. You are right that's exactly what happened. I don't know how to solve it or prevent it in the future yet.
