### ISSUE TITLE
add traffic rules

### ISSUE THREAD

**Issue by old-joker** [miladrahimi/v2ray-docker-compose#56]
can you add routing rule to seprating iran's ip and domain to route directly from iran server (bridge server ) and not routed from upstream server

**Comment by miladrahimi** [comment]
As for .ir domains, it's already exist in:
https://github.com/miladrahimi/v2ray-docker-compose/blob/master/v2ray-bridge-server/config/config.json#L95

As for Iran IPs, it's hard to add all IP ranges but you can add it yourself in your instance.

**Comment by old-joker** [comment]
how can we add something like this rule in config ? 
`"rules": [
    {
      "type": "field",
      "outboundTag": "Direct",
      "ip": [
        "geoip:cn",
        "geoip:private",
        "ext:cn.dat:cn",
        "ext:private.dat:private",
        "ext:geoip-only-cn-private.dat:cn",
        "ext:geoip-only-cn-private.dat:private"
      ]
    }`
https://github.com/Loyalsoldier/geoip
