### ISSUE TITLE
Is there any way to route all traffic through sock or HTTP proxy on linux?

### ISSUE THREAD

**Issue by mahmood8664** [miladrahimi/v2ray-docker-compose#59]
Hi, Sorry if this is not relevant,  Is there any way to route all traffic through sock or HTTP proxy on Linux? I set the HTTP_PROXY but some apps have their config and do not listen to that.

**Comment by miladrahimi** [comment]
The Outline client which supports shadowsocks protocol work like VPN in macOS and Windows, it probably work the same way on Linux. Try it.
See this discussion too:
https://lowendtalk.com/discussion/109239/how-to-route-all-traffic-through-shadowsocks-in-linux-windows
