### ISSUE TITLE
no internet

### ISSUE THREAD

**Issue by arsae** [miladrahimi/v2ray-docker-compose#6]
i do this stuff and no internet both shadowsocks and vmess has no internet access

**Comment by arsae** [comment]
fail to detect internet connection with shadowsocks (v2rayng android client)
fail to detect internet connection context deadline exceded (v2rayng android client)

**Comment by miladrahimi** [comment]
We've tested configurations on many servers. Please check your server configuration and make sure your hosting hasn't blocked your proxy traffic. For example, ArvanCloud blocks ShadowSocks/VMESS traffic, so you cannot run a proxy server there.
