### ISSUE TITLE
Optimizing the Server(s)

### ISSUE THREAD

**Issue by Amirali-Amirifar** [miladrahimi/v2ray-docker-compose#60]
My server is connected and fully working, but using ADSL Internet (LTE not tested) the connection is kind of unstable (Specially on IOS), the connection speed is jumping up and down continuously.
Do you think the optimization articles below could be applicable in this project ?
https://shadowsocks.org/guide/advanced.html
https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks

**Comment by miladrahimi** [comment]
this problem seems not to related to the proxy, it's related to iran internet and the new limitations.
