### ISSUE TITLE
Very Low Speed after 7 Dec 2022

### ISSUE THREAD

**Issue by danaenayati** [miladrahimi/v2ray-docker-compose#65]
Hi 
It seems that the Iranian government blocked or set limitations on the Internet after 7 Dec 2022 which caused decreasing speed.
Is there any solution for fixing that?

Checked with:
-MTN
-MCI
-ZITEL
-ASIATECH
-Mokhaberat

ArvanCloud provides my Iran server.

Thanks,

**Comment by miladrahimi** [comment]
@ohmydevops could you share your exact config of your v2ray/caddy(nginx) please?

**Comment by danaenayati** [comment]
> Use this solution: https://guide.v2fly.org/en_US/advanced/wss_and_web.html#websocket-tls-web
> 
> client(ws+tls) -> iran cdn -> upstream (ws+tls)
> 
> Use Caddy server, for convenience.

Thank you man,

I used the below article and got a good result.
- https://armazopu.github.io/v2ray+websocket+tls+caddy+cdn

It is very easy and simple.

**Comment by ohmydevops** [comment]
> @ohmydevops could you share your exact config of your v2ray/caddy(nginx) please?

https://github.com/miladrahimi/v2ray-docker-compose/pull/69
