### ISSUE TITLE
Nginx config!

### ISSUE THREAD

**Issue by olivehair** [miladrahimi/v2ray-docker-compose#67]
It would be great if you could add nginx configuration as described in https://guide.v2fly.org/en_US/advanced/wss_and_web.html#server-side-configuration for CDN approach.

**Comment by miladrahimi** [comment]
Caddy generates SSL automatically and makes the process super easy. Setting up NGINX needs more documentation and makes it so hard for newbies. It exposes the VMESS 1310 available in localhost so professional users can ignore caddy and use NGINX.

**Comment by miladrahimi** [comment]
Caddy generates SSL automatically and makes the process super easy. Setting up NGINX needs more documentation and makes it so hard for newbies. It exposes the VMESS 1310 available in localhost so professional users can ignore caddy and use NGINX.

**Comment by miladrahimi** [comment]
Caddy generates SSL automatically and makes the process super easy. Setting up NGINX needs more documentation and makes it so hard for newbies. It exposes the VMESS 1310 available in localhost so professional users can ignore caddy and use NGINX.

**Comment by ohmydevops** [comment]
I'm working on this #69
