### ISSUE TITLE
It is not always necessary to use CDN

### ISSUE THREAD

**Issue by ohmydevops** [miladrahimi/v2ray-docker-compose#71]
We can also mention this in the documentation: It is not always necessary to use CDN and users can use WSS (Secure Web Socket) without CDN when there is internet. 
Naturally, they should enable CDN when internet goes down!

**Comment by miladrahimi** [comment]
Currently, exceptionally, the direct connection is slower than connection with cdn/bridge.
CDN/bridge also help servers not to get banned.
I think we should consider it's mandatory to use CDN/bridge.
