### ISSUE TITLE
Error in Use CDN 

### ISSUE THREAD

**Issue by beigi-reza** [miladrahimi/v2ray-docker-compose#78]
I use **V2Ray+CDN+Caddy** And for CDN used **cloudflare**, until the proxy turned off everything is ok.
But when the proxy is turned on after a few minutes (probably the DNS is updated), the connection is interrupted and clients give error **"Fail to detect internet connection: io read/write on closed pipe "** and web page published in the browser (Home page) error **"ERR_TOO_MANY_REDIRECTS"** when page is reloaded

> Caddyfile
```
mydomain.ga {
  root * /usr/share/caddy

  @websockets {
    header Connection *Upgrade*
    header Upgrade    websocket
  }

  reverse_proxy @websockets v2ray:1310/ws

  route {
    reverse_proxy /ws v2ray:1310
    file_server
  }

  log {
    output stdout
  }
}
```

**Comment by miladrahimi** [comment]
It might because of banning cloudflare. Please test arvan cloud.

**Comment by cursedwraith** [comment]
Derak is working well for home internet but for mobile networks im not sure. do we need to activate https cert like we did in arvan cloud ? i could not find it in your instruction @miladrahimi

**Comment by miladrahimi** [comment]
@cursedwraith yes. You have to do the same for any CDN you use. Enabling HTTPS makes it work with CDN and turning on the proxy option makes CDN receive all traffic and pass it to your server so CDN plays bridge server for you.
