### ISSUE TITLE
Simple way to install NekoRay linux client

### ISSUE THREAD

**Issue by ohmydevops** [miladrahimi/v2ray-docker-compose#87]
Users can use this project to install NekoRay with desktop shortcut in most Linux distributions

https://github.com/ohmydevops/nekoray-installer

Simply run:

```wget -qO- https://raw.githubusercontent.com/ohmydevops/nekoray-installer/main/installer.sh | bash```

**Comment by miladrahimi** [comment]
Thanks for your contribution. I've added it to the More section:
https://github.com/miladrahimi/v2ray-docker-compose/blob/master/README.md#more
