### ISSUE TITLE
Important: Arvan CDN limitation

### ISSUE THREAD

**Issue by ohmydevops** [miladrahimi/v2ray-docker-compose#88]
I think it is a good idea to pin this issue for users who using arvan CDN as a bridge.

![Screenshot from 2022-12-31 20-16-10](https://user-images.githubusercontent.com/21690865/210150411-41ec106a-6b0b-4e99-a3db-afaba2ac9506.png)

**Comment by miladrahimi** [comment]
[CDN Free Plans](https://github.com/miladrahimi/v2ray-docker-compose/discussions/89)
