### ISSUE TITLE
Unsupported  'volumes_from'

### ISSUE THREAD

**Issue by aminrsz** [miladrahimi/v2ray-docker-compose#90]
error in docker compose V2RAY_NGINX_CDN:
Unsupported config option for services.dockergen: 'volumes_from'

**Comment by miladrahimi** [comment]
@ohmydevops

**Comment by ohmydevops** [comment]
Upgrade your docker-compose version

**Comment by ohmydevops** [comment]
@aminrsz 

Or wait until I make a fix until 10 o'clock so that old docker-compose versions are supported.

**Comment by aminrsz** [comment]
upgrade docker compose:  fixed
thanks
