### ISSUE TITLE
Monitoring the server

### ISSUE THREAD

**Issue by mfathi91** [miladrahimi/v2ray-docker-compose#92]
Hello,
This is not an issue, rather a question/suggestion. Is there any way to monitor the number of clients that are connected to the bridge/upstream server, and the current network usage?
Thanks

**Comment by miladrahimi** [comment]
Currently, the answer is no for v2ray and yes for the Outline.
Try this:
https://github.com/miladrahimi/v2ray-docker-compose#v2ray-as-outline-bridge-server
It gives a very well-designed manager application (created by Google) to manage your users and the consumed traffic.

**Comment by miladrahimi** [comment]
Currently, the answer is no for v2ray and yes for the Outline.
Try this:
https://github.com/miladrahimi/v2ray-docker-compose#v2ray-as-outline-bridge-server
It gives a very well-designed manager application (created by Google) to manage your users and the consumed traffic.
