### ISSUE TITLE
Is it possible to create PANEL like features?

### ISSUE THREAD

**Issue by NamasteIndia** [miladrahimi/v2ray-docker-compose#93]
Is it possible to create panel like features like managing bandwidth, keeping track on usages, setting time limit for particular uuid, multiple login ban etc using webui?

**Comment by Mchisd** [comment]
@miladrahimi is it possible?

**Comment by miladrahimi** [comment]
If you use the Outline solution, you'll have the Outline Manager app (created by Google) which is a well-designed app to manage what you need. It's also the easiest and most stable solution for now:
https://github.com/miladrahimi/outline-bridge-server

As for v2ray/xray, I recommend you use:
https://github.com/vaxilu/x-ui
